default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  url: postgresql://localhost/github_acessor_development?user=postgres&password=123456

test:
  <<: *default
  url: postgresql://localhost/github_acessor_test?user=postgres&password=123456

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
