default: &default
  client_id: <%= ENV['GITHUB_ACCESSOR_CLIENT_ID'] %>
  redirect_url: 'http://localhost:3001/sessions/create'
  scope: 'user%20repo'
  secret: <%= ENV['GITHUB_SECRET'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

